workspace(name = "io_bazel_rules_rust")

git_repository(
    name = "io_bazel_rules_rust",
    commit = "ee61ddff0b97cfc36278902e5210d1929ba5b119",           
    remote = "https://github.com/bazelbuild/rules_rust.git",
)

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")
rust_repositories()

load("//remote/non_cratesio/cargo:crates.bzl", "non_cratesio_fetch_remote_crates")
non_cratesio_fetch_remote_crates()

load("//remote/complicated_cargo_library/cargo:crates.bzl", "complicated_cargo_library_fetch_remote_crates")
complicated_cargo_library_fetch_remote_crates()

