[workspace]
members = [
    "num_printer",
    "printer",
    "rng",
]

[workspace.metadata.raze]
workspace_path = "//remote/cargo_workspace/cargo"
gen_workspace_prefix = "remote_cargo_workspace"
genmode = "Remote"
default_gen_buildrs = true
