[package]
name = "no_deps"
version = "0.1.0"
authors = ["UebelAndre <github@uebelandre.com>"]

[[bin]]
name = "no_deps"
path = "src/main.rs"

[raze]
workspace_path = "//remote/no_deps/cargo"
genmode = "Remote"
incompatible_relative_workspace_path = true
gen_workspace_prefix = "remote_no_deps"
