[package]
name = "num_printer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "number-printer"
path = "src/main.rs"

[dependencies]
clap = "2.33.3"
printer = { path = "../printer" }
